Update dev Dockerfiles

diff --git a/Dockerfile_local_smash_basic_dev b/Dockerfile_local_smash_basic_dev
--- a/Dockerfile_local_smash_basic_dev
+++ b/Dockerfile_local_smash_basic_dev
@@ -3,16 +3,23 @@
 FROM ubuntu:22.04
 
 # Set bash as the default shell in this Dockerfile
+
 SHELL ["/bin/bash", "-c"]
+
+# Set the proper general cpu family architecture flag.
+# Please, for more information refer to the documention of your compiler.
+
+ARG TARGET_ARCHITECTURE="x86-64"
 
 # Add some info about authors and contents
 
-LABEL maintainer.name="SMASH team"
-LABEL maintainer.website="https://smash-transport.github.io"
-LABEL description="Basic SMASH image (sources, compiler and bare executable, without ROOT, HepMC3 and Rivet)."
+LABEL org.opencontainers.image.maintainer.name="SMASH team"
+LABEL org.opencontainers.image.maintainer.website="https://smash-transport.github.io"
+LABEL org.opencontainers.image.description="Basic SMASH image (sources, compiler and bare executable, without ROOT, HepMC3 and Rivet)."
 LABEL org.opencontainers.image.source https://github.com/smash-transport/smash
 
 # Install minimal set of requirements
+
 RUN apt-get update && \
 apt-get -y upgrade && \
 DEBIAN_FRONTEND=noninteractive apt-get -y install \
@@ -26,19 +33,26 @@ rsync \
 wget \
 vim
 
+# Set cpu architecture flag for compilation
+
+ARG C_CXX_ARCH_FLAG="-march=${TARGET_ARCHITECTURE}"
+
 # Create main project directory
+
 WORKDIR /SMASH
 
 # Create directory for mounting filesystems
+
 RUN mkdir /MNT
 
 # Install pythia
+
 ARG pythiaV="8310"
 ENV PYTHIA8=/SMASH/pythia_install/
 RUN wget https://pythia.org/download/pythia83/pythia${pythiaV}.tgz && \
 tar xf pythia${pythiaV}.tgz && rm pythia${pythiaV}.tgz && \
 cd pythia${pythiaV} && \
-./configure --cxx-common='-std=c++17 -mfpmath=sse -O3 -fPIC -march=x86-64 -pthread' --prefix=${PYTHIA8} && \
+./configure --cxx-common="${C_CXX_ARCH_FLAG} -O3 -std=c++17 -fPIC -pthread" --prefix=${PYTHIA8} && \
 make -j$(nproc) && \
 make install && \
 echo ${PYTHIA8}/lib >> /etc/ld.so.conf && ldconfig
@@ -51,14 +65,14 @@ ENV PATH=$PYTHIA8/bin:$PATH
 
 # we copy the currently checked branch of the local smash-devel sources into the /SMASH directory
 COPY smash-devel /SMASH/smash
- 
+
 # Get and build public SMASH
 RUN cd /SMASH && \
 mkdir -p smash/build && \
 mkdir -p smash_bin && \
 cd smash/build && \
-cmake .. -DPythia_CONFIG_EXECUTABLE=/SMASH/pythia${pythiaV}/bin/pythia8-config -DCMAKE_C_FLAGS="-march=x86-64" -DCMAKE_CXX_FLAGS="-march=x86-64" \
-|| echo "cmake SMASH build configuration failed!"
+cmake .. -DPythia_CONFIG_EXECUTABLE=/SMASH/pythia${pythiaV}/bin/pythia8-config -DCMAKE_C_FLAGS="${C_CXX_ARCH_FLAG}" \
+-DCMAKE_CXX_FLAGS="${C_CXX_ARCH_FLAG}" || echo "cmake SMASH build configuration failed!"
 RUN cd /SMASH/smash/build && make smash -j$(nproc) || echo "make SMASH compilation failed!"
 RUN <<EOF
 if [ -f /SMASH/smash/build/smash ]
