Updated Dockerfiles for dev version

diff --git a/Dockerfile_smash_basic_dev b/Dockerfile_smash_basic_dev
--- a/Dockerfile_smash_basic_dev
+++ b/Dockerfile_smash_basic_dev
@@ -1,3 +1,5 @@
+# syntax=docker/dockerfile:1.4
+
 FROM ubuntu:22.04
 
 # Set bash as the default shell in this Dockerfile
@@ -18,7 +20,6 @@ bash \
 cmake \
 git \
 g++ \
-libboost-all-dev \
 libeigen3-dev \
 libgsl-dev \
 rsync \
@@ -46,15 +47,23 @@ ENV LD_LIBRARY_PATH=$PYTHIA_LIBRARY:$LD_LIBRARY_PATH
 ENV PATH=$PYTHIA8/bin:$PATH
 
 # Get and build public SMASH
-RUN git clone https://github.com/smash-transport/smash.git && \
+RUN cd /SMASH && git clone https://github.com/smash-transport/smash.git && \
 mkdir -p smash/build && \
 mkdir -p smash_bin && \
 cd smash/build && \
-cmake .. -DPythia_CONFIG_EXECUTABLE=/SMASH/pythia${pythiaV}/bin/pythia8-config && \
-make smash -j$(nproc) && \
-cp smash  /SMASH/smash_bin/ && \
-cp config.yaml /SMASH/smash_bin/ && \
-rm -r /SMASH/smash/build
+cmake .. -DPythia_CONFIG_EXECUTABLE=/SMASH/pythia${pythiaV}/bin/pythia8-config -DCMAKE_C_FLAGS="-march=x86-64" -DCMAKE_CXX_FLAGS="-march=x86-64" \
+|| echo "cmake SMASH build configuration failed!"
+RUN cd /SMASH/smash/build && make smash -j$(nproc) || echo "make SMASH compilation failed!"
+RUN <<EOF
+if [ -f /SMASH/smash/build/smash ]
+then
+  cp /SMASH/smash/build/smash /SMASH/smash_bin/
+  cp /SMASH/smash/build/config.yaml /SMASH/smash_bin/
+  rm -r /SMASH/smash/build
+else
+  rm -r /SMASH/smash /SMASH/smash_bin
+fi
+EOF
 
 # Set PATH
 
